### ISSUE TITLE
Некорректный перевод

### ISSUE THREAD

**Issue by JohnScience** [rust-lang-ru/book#1111]
В [4.3 тип среза](https://doc.rust-lang.ru/book/ch04-03-slices.html) есть [упоминание некого "дополнительного бита"](https://doc.rust-lang.ru/book/ch04-03-slices.html#:~:text=%2C%20%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%BD%D1%83%D1%8E%20%D0%B2-,%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC%20%D0%B1%D0%B8%D1%82%D0%B5,-%5B0..5%5D). 

![скриншот](https://i.imgur.com/iiY78ki.png)

Вероятно ошибка произошла из-за некорректного перевода слова bit (которое в данном случае значит "малая часть" а не "двоичный бит"). Предлагаю альтернативый перевод: "в дополнительном кусочке синтаксиса" `[0..5]`.

P.S. Я постарался сделать изменение через GitLocalize, но не разобрался и решил вместо этого оставить issue.

**Comment by ava57r** [comment]
там еще оригинал обновился.
перевел всю страницу и внес ваше предложение
