### ISSUE TITLE
Нарушение вёрстки Markdown в GitLocalize

### ISSUE THREAD

**Issue by dluschan** [rust-lang-ru/book#1166]
Наблюдаю проблему, которая, похоже, носит систематический характер.
GitLocalize не даёт редактировать "сырой" файл Markdown, а предлагает лишь работать с его "красивым" представлением. Это приводит к ошибкам в разметке. Если есть способ в GitLocalize работать с исходным файлом явно, надо это добавить в инструкцию, потому что на текущий момент не понятно, как можно исправить обнаруженные проблемы.

В качестве примера можно сравнить последний абзац файла ch03-00-common-programming-concepts.md.
Оригинал (https://github.com/rust-lang-ru/book/blob/master/rustbook-en/src/ch03-00-common-programming-concepts.md?plain=1):
> #### Keywords
>
> The Rust language has a set of *keywords* that are reserved for use by the
> language only

Перевод (https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch03-00-common-programming-concepts.md?plain=1):
> <h>Ключевые слова</h> В языке Rust как и в других языках есть набор *ключевых слов*, зарезервированных

**Comment by funkill** [comment]
Привет
Похоже это тот случай, когда надо отписаться в GitLocalize о багах. Сделать это можно [тут](https://github.com/gitlocalize/feedback/issues)

**Comment by dluschan** [comment]
Кажется, я разобрался и проблемы в работе GitLocalize не наблюдается.
Если я правильно понял, то при клике в непереведённый абзац, система даёт что-то вроде исходного текста вперемежку с псевдо-html тегами со встроенными в них номерами.
В таком случае ошибка в приведённом выше случае могла быть сделана переводчиком а не системой, и ругать GitLocalize не за что.
Тогда встречающиеся расхождения можно исправлять непосредственно в GitLocalize, а этот Issue закрывать.

**Comment by dluschan** [comment]
Если же кто-то встречал случаи, где их система представления Markdown (или других форматов) не достаточно для перевода с сохранением структуры, то, конечно, надо завести у них баг, но я пока такого не встречал.
