### ISSUE TITLE
Использование тире

### ISSUE THREAD

**Issue by dluschan** [rust-lang-ru/book#1169]
Добырй день.
Предлагаю в "Правила участия в переводе" CONTRIBUTING.md добавить правила использования тире в переводе и о том, что оно должно быть "длинным" (em dash) по умолчанию.

**Comment by funkill** [comment]
@TelegaOvoshey fyi

**Comment by TelegaOvoshey** [comment]
Я думаю, это отличное правило) Главное, чтобы оно не грузило переводчиков еще больше. По умолчанию в виндовой раскладке нет быстрой клавиши для тире, вставлять его довольно трудоемкое занятие. 

В качестве альтернативы можно предложить по окончании перевода проходиться автозаменой типа "пробел-дефис-пробел" на "пробел-тире-пробел"

**Comment by dluschan** [comment]
Готово — https://github.com/rust-lang-ru/book/pull/1171
