### ISSUE TITLE
Кривое окончание

### ISSUE THREAD

**Issue by zhenyamega** [rust-lang-ru/book#1197]
На странице `ch04-02-references-and-borrowing` есть предложение:

```
В один момент времени, может существовать либо одна изменяемая ссылка, либо любое количество неизменяемых ссылка
```

Вот `неизменяемых ссылка` звучит странно.

**Comment by AndyBrizhak** [comment]
В один момент времени, может существовать либо одна изменяемая (mutable) ссылка, либо любое количество неизменяемых (immutable) ссылок
