### ISSUE TITLE
Тире и дефисы

### ISSUE THREAD

**Issue by dluschan** [rust-lang-ru/book#1251]
Здесь https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/appendix-01-keywords.md
в нарушение Соглашения о процессе перевода (https://github.com/rust-lang-ru/book/blob/master/CONTRIBUTING.md) тире и Дефисы используются в перемешку. Исправить на https://gitlocalize.com/repo/4579/ru/rustbook-en/src нельзя — нет прав.

**Comment by ava57r** [comment]
надо подумать. на глаз в GL это не увидеть, а автоматизировано по данным Gl не пройти.

**Comment by ava57r** [comment]
вручную такие тире в GL отыскивать можно до тошноты.
Делать через GH бесмысслено, так как GL не подтягивает изменений.

Предлагаю пока оставить как есть.

**Comment by dluschan** [comment]
Сейчас файл в порядке. Это issue можно закрыть как выполненное.
