### ISSUE TITLE
Неверные сведения о языках C и C++ и ошибка перевода

### ISSUE THREAD

**Issue by maxmosk** [rust-lang-ru/book#1299]
1. Дублирую это: https://github.com/rust-lang/book/issues/3761
2. Также перепутаны указатели и ссылки здесь же: https://github.com/rust-lang-ru/book/blob/d489bab2066217e91945199b2e5a2c6af464e70a/rustbook-ru/src/ch05-03-method-syntax.md?plain=1#L39

Предлагаю просто исправить параллельно с исправлением оригинала. Могу (и хочу) это сделать.

**Comment by ava57r** [comment]
это issue, не исправление конкретного файла.
Мне необходимо именно оно
