### ISSUE TITLE
Ошибка в указании листинга

### ISSUE THREAD

**Issue by exynil** [rust-lang-ru/book#227]
Раздел 3.5: Управление выполнением кода

_Так как if является выражением, то его можно использовать в правой части кода оператора let, как в листинге 3-2._

В разделе отсутствует листинг 3-2 или не правильно указан номер листинга.

**Comment by andreevlex** [comment]
Спасибо!

**Comment by andreevlex** [comment]
Этот момент не совсем ясный.
В оригинале вижу 3-2.
Возможно в обновленной версии оригинала поправили.
Подождем
