### ISSUE TITLE
Ошибка в переводе

### ISSUE THREAD

**Issue by nntndfrk** [rust-lang-ru/book#259]
Раздел 10.2. Типажи: определение общего поведения

Ошибка в листинге 10-12:
`pub trait Summarizable {
    fn summary(&self) -> String;
}`

В оригинале:
`pub trait Summary {
    fn summarize(&self) -> String;
}`

**Comment by andreevlex** [comment]
Посмотрим. Спасибо. Возможно ошибки синхронизации с оригиналом.

**Comment by andreevlex** [comment]
https://github.com/rust-lang-ru/book/pull/269
