### ISSUE TITLE
Хэш-карты и HashMap

### ISSUE THREAD

**Issue by deadblackclover** [rust-lang-ru/book#279]
В тексте используется и "хэш-карты" и "HashMap" вперемешку. Мне кажется лучше не использовать "хэш-карты", так как такое название сбивает с толку. А также будет одна стилистика.

**Comment by andreevlex** [comment]
HashMap по мне лучше.

**Comment by blandger** [comment]
пушнул в мастер изменения, не знаю, надо ли было через локальную ветку + PR ??
если надо - то считаем что я "тупанул". в след.раз сделаю в форке.

**Comment by blandger** [comment]
https://github.com/rust-lang-ru/book/commit/3af7132e5211311c38022aea7239f145f1300eeb

**Comment by andreevlex** [comment]
В след. раз предложил бы через PR.

**Comment by andreevlex** [comment]
И если отправил в мастер, то при обновлении через GL эти изменения затрутся...

**Comment by deadblackclover** [comment]
Но на https://doc.rust-lang.ru/book/ch08-03-hash-maps.html ничего не изменилось. У вас публикация не автоматическая?

**Comment by andreevlex** [comment]
не автоматическая

**Comment by funkill** [comment]
@andreevlex уже есть: когда автоматическое обновление оригинала добавили, тогда же и деплой появился. Только поломался видимо

**Comment by funkill** [comment]
Исправлено

**Comment by deadblackclover** [comment]
Увидел. Предлагаю закрыть issues.
