### ISSUE TITLE
A typo related to get access for whole slice in rustbook-ru/src/ch04-03-slices.md

### ISSUE THREAD

**Issue by freishutz** [rust-lang-ru/book#281]
[anovik@arch-vm0 rust-book.git]$ diff -Naru /tmp/ch04-03-slices.md.orig /tmp/ch04-03-slices.md.patched 
--- /tmp/ch04-03-slices.md.orig 2020-07-01 17:52:32.906833243 +0300
+++ /tmp/ch04-03-slices.md.patched      2020-07-01 17:50:31.040170335 +0300
@@ -149,8 +149,8 @@
Также можно не указывать оба значения, чтобы получить срез всей строки. Это эквивалентно:

```rust
let s = String::from("hello");
 
 let len = s.len();
 
-let slice = &s[3..len];
-let slice = &s[3..];
+let slice = &s[0..len];
+let slice = &s[..];
 ```
 
 > Внимание: Индексы среза строк должны соответствовать границам UTF-8 символов. Если вы попытаетесь получить срез нарушая границы символа в котором больше одного байта, то вы получите ошибку времени исполнения. В рамках этой главы мы будем предполагать только ASCII кодировку. Более детальное обсуждение UTF-8 находится в секции ["Сохранение текста с кодировкой UTF-8 в строках"] главы 8.
@@ -301,4 +301,4 @@
 Владение влияет на множество других частей и концепций языка Rust. Мы будем говорить об этих концепциях на протяжении оставшихся частей книги. Давайте перейдём к главе 5 и рассмотрим группировку частей данных в структуры `struct`.
 
 
-["Сохранение текста с кодировкой UTF-8 в строках"]: ch08-02-strings.html#storing-utf-8-encoded-text-with-strings
\ В конце файла нет новой строки
+["Сохранение текста с кодировкой UTF-8 в строках"]: ch08-02-strings.html#storing-utf-8-encoded-text-with-strings

**Comment by blandger** [comment]
@freishutz 
Подготовил обновленный ПР по этой главе.
Просьба еще раз просмотреть текст до мержа его в гит

https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch04-03-slices.md

**Comment by freishutz** [comment]
@blandger 
Коммиту -2 ибо пример не поправлен.
