### ISSUE TITLE
Multiple typos in rustbook-ru/src/ch05-01-defining-structs.md

### ISSUE THREAD

**Issue by freishutz** [rust-lang-ru/book#282]
1. месте - **в**месте (together);
2. везде **,** где (need a comma);

Для определения структуры, указывается ключевое слово `struct` и её название. Название должно описывать значение частей данных сгруппированных **в**месте. 
 
Чтобы получить определённое значение поля структуры, мы можем использовать точечную нотацию (как в кортеже). Если нужен только электронный адрес, можно использовать `user1.email` везде **,** где нужно его значение.

[ch05-01-defining-structs.md.patch.txt](https://github.com/rust-lang-ru/book/files/4858922/ch05-01-defining-structs.md.patch.txt)

Also, this is a really strange construction (using **;**) :

`
Заметим, что весь экземпляр структуры должен быть изменяемым; Rust не позволяет помечать изменяемыми отдельные поля.
`
I guess we should have either a comma or new sentence here. This is actual for English version of the book too.

**Comment by blandger** [comment]
перенес эти мелкие правки в пул
https://gitlocalize.com/repo/4579/ru/review/17790
здесь можно закрывать после мержа
