### ISSUE TITLE
Misprint in rustbook-ru/src/ch08-02-strings.md

### ISSUE THREAD

**Issue by TicTak21** [rust-lang-ru/book#298]
Раздел: [Индексирование в строках](https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch08-02-strings.md#%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B0%D1%85)

1. Всё равно вы получить ошибку при попытке получить доступ... - Однако, вы всё равно получите ошибку при попытке получить доступ...

До(в контесте абзаца): 
Доступ к отдельным символам в строке, ссылаясь на них по индексу, является допустимой и распространённой операцией во многих других языках программирования. **Всё равно вы получить ошибку при попытке получить доступ** к частям String, используя синтаксический индекс в Rust. Рассмотрим неверный код в листинге 8-19.

После(в контесте абзаца): 
Доступ к отдельным символам в строке, ссылаясь на них по индексу, является допустимой и распространённой операцией во многих других языках программирования. **Однако, вы всё равно получите ошибку при попытке получить доступ** к частям String, используя синтаксический индекс в Rust. Рассмотрим неверный код в листинге 8-19.

**Comment by blandger** [comment]
внес изменения в 
https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch08-02-strings.md
потом закроем

**Comment by blandger** [comment]
готово
