### ISSUE TITLE
Разрешение конфликтов

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/book#3]
На данный момент, не все конфликты сопоставления оригинала и перевода разрешены.

Необходимо удалить то, что не соответствует оригиналу и сопоставить оставшееся.

- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/appendix-01-keywords.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/appendix-02-operators.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch01-01-installation.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch01-02-hello-world.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch02-00-guessing-game-tutorial.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-00-common-programming-concepts.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-01-variables-and-mutability.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-02-data-types.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-03-how-functions-work.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-05-control-flow.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch04-01-what-is-ownership.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch04-02-references-and-borrowing.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch04-03-slices.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch05-01-defining-structs.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch05-02-example-structs.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch05-03-method-syntax.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch06-01-defining-an-enum.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch06-02-match.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch06-03-if-let.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch08-01-vectors.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch08-02-strings.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch08-03-hash-maps.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch09-01-unrecoverable-errors-with-panic.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch09-02-recoverable-errors-with-result.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch09-03-to-panic-or-not-to-panic.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch10-00-generics.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch10-01-syntax.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch10-02-traits.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch10-03-lifetime-syntax.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch11-00-testing.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch11-01-writing-tests.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch11-02-running-tests.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-01-accepting-command-line-arguments.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-02-reading-a-file.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-03-improving-error-handling-and-modularity.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-04-testing-the-librarys-functionality.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-05-working-with-environment-variables.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-06-writing-to-stderr-instead-of-stdout.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch13-01-closures.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch13-02-iterators.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch13-03-improving-our-io-project.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch13-04-performance.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch14-03-cargo-workspaces.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-00-smart-pointers.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-01-box.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-02-deref.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-03-drop.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-04-rc.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-05-interior-mutability.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch15-06-reference-cycles.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch16-00-concurrency.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch16-01-threads.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch16-02-message-passing.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch16-03-shared-state.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch17-01-what-is-oo.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch17-02-trait-objects.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch17-03-oo-design-patterns.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch18-01-all-the-places-for-patterns.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch18-02-refutability.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch18-03-pattern-syntax.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch19-01-unsafe-rust.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch19-03-advanced-traits.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch19-04-advanced-types.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch19-05-advanced-functions-and-closures.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch20-00-final-project-a-web-server.md
- [x] https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch20-01-single-threaded.md

**Comment by bigov** [comment]
Не получается разрешить конфликты в https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch12-02-reading-a-file.md. Все лагает. Пробовал править и в Хроме и в Эдже - результат аналогичный. Наверно, надо просто удалить перевод этой главы и перевести по новой - там не так много.

**Comment by funkill** [comment]
С удалением у них есть проблемы, по всей видимости, только модераторы могут удалять. Поправил
