### ISSUE TITLE
Неверный пример кода.

### ISSUE THREAD

**Issue by orenjihokage** [rust-lang-ru/book#444]
В абзаце говориться про добавление треугольных скобок, но в примере кода их нет.
https://doc.rust-lang.ru/book/ch10-01-syntax.html#%D0%92-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9
![Screenshot 2020-12-27 105534](https://user-images.githubusercontent.com/56073655/103166448-2c60b780-4833-11eb-8438-5b0cd7979d1d.png)

**Comment by ava57r** [comment]
сейчас в книге на GH нет такого перевода

**Comment by ava57r** [comment]
у нас версия из GH не грузится онлайн на https://doc.rust-lang.ru/

**Comment by ava57r** [comment]
https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch10-01-syntax.md такого в абзаце не нашел.

**Comment by SomeAkk** [comment]
@orenjihokage есть такая проблема, видимо @ava57r не заметил. Добавил скриншот с соответствующей ссылкой ниже. В ближайшее время доберусь до этого раздела и внесу правки.
![Снимок экрана 2021-01-01 в 18 26 35](https://user-images.githubusercontent.com/57045709/103441469-346b8d80-4c5f-11eb-9b04-15e513062922.png)

**Comment by SomeAkk** [comment]
@orenjihokage исправления добавлены в рамках pr https://github.com/rust-lang-ru/book/pull/545

**Comment by SomeAkk** [comment]
@funkill можно закрывать проблему: книга обновлена и включает нужное исправление.

https://doc.rust-lang.ru/book/ch10-01-syntax.html
