### ISSUE TITLE
Исправление опечаток и ошибок

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/book#5]
https://travis-ci.org/ruRust/book/builds/583894692

**Comment by blandger** [comment]
Так разве что-то еще билдится? по ссылке - пустота...

**Comment by funkill** [comment]
Уже нет: у нас другое имя организации стало, мы переехали на github actions да и сейчас по каждому PR'у проверка делается (до этого вся книга на каждый PR проверялась)
