### ISSUE TITLE
Нет листинга 9-10

### ISSUE THREAD

**Issue by 1vanK** [rust-lang-ru/book#707]
https://doc.rust-lang.ru/book/ch09-03-to-panic-or-not-to-panic.html
![1](https://user-images.githubusercontent.com/13021826/150662316-8e681b8d-6d04-4465-9b2f-ae719790cb68.png)

**Comment by blandger** [comment]
Англ.оригинал уже содержит ссылку на другой файл примера и номер другой.

```rust
{{#include ../listings/ch09-error-handling/listing-09-13/src/main.rs:here}}
```
<span class="caption">Listing 9-13: A `Guess` type that will only continue with
values between 1 and 100</span>


Русский устарел, надо править, наверное в GL сначала посмотреть.

```rust
{{#include ../listings/ch09-error-handling/listing-09-10/src/main.rs:here}}
```
<span class="caption">Листинг 9-10. Тип <code>Guess</code>, который будет создавать экземпляры только для значений от 1 до 100</span>

**Comment by blandger** [comment]
https://github.com/rust-lang-ru/book/pull/708

**Comment by blandger** [comment]
fixed
