### ISSUE TITLE
Небольшая ошибка в переводе (раздел 5.1)

### ISSUE THREAD

**Issue by Annet8** [rust-lang-ru/book#718]
В описании говорится, что мы устанавливаем новые значения для email и username, в коде же новое значение устанавливается только для email. 
![46077968-36D5-40F9-B66C-2382B5AFFDB1](https://user-images.githubusercontent.com/83312630/152611578-28e23490-35c2-42bf-a9ba-fd1675cfb108.jpeg)
![38CC57FE-C7CB-4D9E-9563-0929646417E9](https://user-images.githubusercontent.com/83312630/152611589-d39faa59-f36a-4f05-a3ac-f6e3c9b0cd2b.jpeg)

**Comment by blandger** [comment]
![image](https://user-images.githubusercontent.com/274803/152638393-d8788714-b5c7-4612-9a88-b36d8d2d57f9.png)
В переводе GL все корректно написано, достаточно просто обновить GH новым содержимым и если книга собирается "автоматом", то корректный текст будет на сайте. Обновление GH сделаю.

**Comment by blandger** [comment]
поправил в
https://github.com/rust-lang-ru/book/pull/721
