### ISSUE TITLE
Поломались листинги кода

### ISSUE THREAD

**Issue by art-den** [rust-lang-ru/book#788]
Не выводяться листниги в некоторых местах. Например на https://doc.rust-lang.ru/book/ch13-02-iterators.html

Вместо текста показывает строку
```
{{#rustdoc_include ../listings/ch13-functional-features/listing-13-13/src/main.rs:here}}
```

**Comment by funkill** [comment]
Исправление тут: https://github.com/rust-lang-ru/books/pull/16
Пока не мержу, надо ещё сборку проверить.
Часть листингов поломано из-за того, что текст главы устарел и соответствующих файлов с кодом уже не существует

**Comment by ava57r** [comment]
Добрый день.
Да есть большое расогласование оригинала и перевода.
Оригинал подливается роботом новый каждый день, а переводим мы не так оперативно.

**Comment by funkill** [comment]
Закрою в пользу задачи https://github.com/rust-lang-ru/book/issues/792. Основная причина смещения листингов - устаревание перевода.
