### ISSUE TITLE
Смещены листинги кода в п. 8.1

### ISSUE THREAD

**Issue by RusakDmitry** [rust-lang-ru/book#816]
Нашел несоответствие в раст бук на русском в [главе 8, пункте 8.1.](https://doc.rust-lang.ru/book/ch08-01-vectors.html) В книге на английском в этом месте говорится про [заимствование](https://doc.rust-lang.org/book/ch08-01-vectors.html) в элемента вектора. А в книге на русском не соответствует код, в коде нет обращения к сотому элементу. Но основное, что код не соответствует описанию
![image](https://user-images.githubusercontent.com/25077787/172007430-ae652968-543b-4850-b403-1118dedf32f5.png)

В русском переводе смещение листингов на 1 вверх
![image](https://user-images.githubusercontent.com/25077787/172007515-764a2664-ca84-4d2c-bbb5-c394b03497d6.png)
![image](https://user-images.githubusercontent.com/25077787/172007535-acaaf19e-73fe-4c84-94e6-5f4c8c4976e3.png)

А конкретно из этого места "Удаление вектора - удаляет все его элементы" все поплыло
![image](https://user-images.githubusercontent.com/25077787/172007671-87a2a7e3-4f5d-40b5-aca2-968d0bc577b1.png)
![image](https://user-images.githubusercontent.com/25077787/172007684-ddd42cb3-d5ab-4df7-aed3-d84dd5de05cd.png)

Спасибо!)

**Comment by ava57r** [comment]
Добрый день.
Да есть большое расогласование оригинала и перевода.
Оригинал подливается роботом новый каждый день, а переводим мы не так оперативно.

**Comment by RusakDmitry** [comment]
@ava57r все равно отличный перевод! красавчики) я просто обратил ваше внимание на это)

**Comment by funkill** [comment]
Закрою в пользу задачи https://github.com/rust-lang-ru/book/issues/792. Основная причина смещения листингов - устаревание перевода.
