### ISSUE TITLE
Битая ссылка {const_eval}

### ISSUE THREAD

**Issue by locaIhost** [rust-lang-ru/book#901]
В этом файле https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/src/ch03-01-variables-and-mutability.md  битая ссылка в тексте "См [раздел справочника Rust, посвящённый вычислению констант](https://github.com/rust-lang-ru/book/blob/master/rustbook-ru/reference/const_eval.html)"
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Есть ли перевод? в английской версии всё норм, отличие только с доменом.

**Comment by funkill** [comment]
Перевод справочника? Его нет.

Добавил редирект на оригинал справочника.
